backend:
  name: github
  repo: dinuraweli/church-website   # your GitHub repo
  branch: main
  base_url: https://church-website2.netlify.app
  auth_type: implicit

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "pages"
    label: "Pages"
    folder: "content/pages"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
