backend:
  name: github
  repo: dinuraweli/church-website # Example: lehanwelikala/church-website
  branch: main
  auth_scope: repo
  base_url: https://api.netlify.com
  auth_endpoint: /auth
media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Home Page"
        name: "index"
        file: "index.html"
        fields:
          - { label: "Page Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
